name: syhunt test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - uses: actions/checkout@v4
      - run: ScanURL -target 'http://localhost:8080' -pfcond 'fail-if:risk=mediumup' -output 'report.pdf'
      - name: 'Syhunt Report'
        uses: actions/upload-artifact@v4
        if: failure()
        with:
         name: syhunt-report
         path: report.pdf
         if-no-files-found: error