name: Deploy Application WBio

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
  
            - name: Aplicação WBio
              uses: actions/setup-node@v3
              with:
                node-version: 22
                cache: 'npm'
                cache-dependency-path: package-lock.json
            - name: Install dependencies
              run: npm install
            - name: Login Docker Hub
              run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
            - name: Build docker image
              run: docker build -t brunotavaresssssasasasas/aws-docker .
            - name: Push image docker
              run: docker push brunotavaresssssasasasas/aws-docker